language: python
jobs:
  include:
  - name: Python 3.8 on Linux
    python: 3.8
    before_install:
    - sudo apt-get -yq update &&  sudo apt-get -yq install upx
  - name: Python 3.8 on macOS
    os: osx
    osx_image: xcode11.2
    language: shell
    before_install:
    - pyenv install 3.8.2 && pyenv global system 3.8.2
    - echo 'eval "$(pyenv init -)"' >> ~/.bashrc
  - name: Python 3.8 on Windows
    os: windows
    language: bash
    before_install:
    - choco install python --version=3.8.2
    - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
install:
- pip3 install -r build/requirements.txt
- pip3 install pyinstaller
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip3 install pypiwin32 pefile; fi
script:
- pushd build; ./package.sh; popd
deploy:
  provider: releases
  api_key:
    secure: Ik0ZF2El5ffjYGdSCK2bbAlykib7gAVD5B0w0OdtfdoJ7qpW9EnYj2dgRCQBhrXah+vzF7zM2aSBaCr5C4ra7Nl0X0S42/oo7ReNZnn7YSSYf0/rfNcKrfcnnOOsQXARlWieB1IFJnV74Wxu6k6YcXtkhAjyQ8cqu6ONcnpKnyzJwi2ZgKigdf/015XrntdIizP9Qa7b6tz6OF8gTzIz8LmVWmGkJjrpZ4JkSymmRBr9/D/V72X5+Cn1mJlg/3sZTnETxZXVGYIWIv8cxpi8xd/kPdzFGxuLbD1KBaYJQzE6FAGFNn3bAvuDMQ6f+0tlJKjkbWBq8LDI6oAYeDV/fJH0cMugW9Ci2zWZHgI0J38Be8eHU21muJOKPXVXxg1sY3Pr1078Riq+Jx1QWXIBUBs+u3ktx8QLbVtAzwqLLJ/z3dtF2PsBPyC4KpkjN2MUysxceMonDeqgqjKftJSzi9dP8LMEG6m3iGuAFyCGoqmRGK3jU8n3NeOjI3AdX7Gw2oMg/+DWtq8SxlLEWG2mZfb5HKEjZqr5aO1hgCjOQ1ToDx4n3z1TOgcHXDr+twqS/8+tGsdDV1wP3FnqMZbsPTfAXIt6oGbHwaBSwsr23rirDRtohnsh2ThHgMhtoFjS5dV1krAFFyrQjphHTTWzsz1vj5KnX0s4J+ZutwMrGdE=
  skip_cleanup: true
  draft: true
  file_glob: true
  file: dist/wildfire-maps_*
  on:
    tags: true
